#!/usr/bin/expect -f
set timeout -1
spawn ./run_rl_swarm.sh
expect {
    "connect to the Testnet? \\Y/n\\" {
        send "Y\r"
        exp_continue
    }
    "math problem" {
        send "A\r"
        exp_continue
    }
    "parameters.*:" {
        send "7\r"
        exp_continue
    }
    "hugging.*token.*\Y/n\" {
        send "N\r"
        exp_continue
    }
    "OTP:" {
        interact
    }
}
